// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJLRR.Models;

#nullable disable

namespace PROJLRR.Migrations
{
    [DbContext(typeof(PerslrrsanscodeContext))]
    [Migration("20260527215008_FixBase1Key")]
    partial class FixBase1Key
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PROJLRR.Models.Article", b =>
                {
                    b.Property<int?>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int?>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StockSec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unite")
                        .HasColumnType("VARCHAR(255)");

                    b.ToTable("ARTICLE", (string)null);
                });

            modelBuilder.Entity("PROJLRR.Models.Base1", b =>
                {
                    b.Property<int>("Num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("CEMAV");

                    b.Property<string>("Cin")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("CIN");

                    b.Property<string>("Contact")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("CONTACT");

                    b.Property<string>("Corps")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("CORPS");

                    b.Property<string>("Datedentre")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DATEDENTRE");

                    b.Property<string>("Datedeprise")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DATEDEPRISE");

                    b.Property<string>("Datenaiss")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DATENAISS");

                    b.Property<string>("Dec")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DEC");

                    b.Property<string>("Demav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DEMAV");

                    b.Property<string>("Diplomeac")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DIPLOMEAC");

                    b.Property<string>("Diplomeped")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DIPLOMEPED");

                    b.Property<string>("Dou")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DOU");

                    b.Property<string>("Dxemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DXEMAV");

                    b.Property<string>("Fonction")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("FONCTION");

                    b.Property<string>("Hemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("HEMAV");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lieudenaiss")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LIEUDENAISS");

                    b.Property<string>("Matiere")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("MATIERE");

                    b.Property<string>("Matricule")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("MATRICULE");

                    b.Property<string>("Nemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("NEMAV");

                    b.Property<string>("NomEtPrenoms")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("NOM_ET_PRENOMS");

                    b.Property<string>("Onemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("ONEMAV");

                    b.Property<string>("Perav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("PERAV");

                    b.Property<string>("Photo")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Qemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("QEMAV");

                    b.Property<string>("Quat")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("QUAT");

                    b.Property<string>("Quin")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("QUIN");

                    b.Property<string>("Seiz")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SEIZ");

                    b.Property<string>("Semav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SEMAV");

                    b.Property<string>("Sepmav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SEPMAV");

                    b.Property<string>("Sexe")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SEXE");

                    b.Property<string>("Statut")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("STATUT");

                    b.Property<string>("Temav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("TEMAV");

                    b.Property<string>("Trei")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("TREI");

                    b.HasKey("Num");

                    b.ToTable("BASE1", (string)null);
                });

            modelBuilder.Entity("PROJLRR.Models.Decharge", b =>
                {
                    b.Property<string>("ArticleNom")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<long?>("DateDecharge")
                        .HasColumnType("TIMESTAMP(26)");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("PersonnelNom")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int?>("Quantite")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QUANTITE");

                    b.Property<string>("SignaturePath")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Unite")
                        .HasColumnType("VARCHAR(255)");

                    b.ToTable("DECHARGE", (string)null);
                });

            modelBuilder.Entity("PROJLRR.Models.Personnel", b =>
                {
                    b.Property<int>("Num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Num");

                    b.Property<string>("Cemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("CEMAV");

                    b.Property<string>("Cin")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("CIN");

                    b.Property<string>("Contact")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("CONTACT");

                    b.Property<string>("Corps")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("CORPS");

                    b.Property<string>("Datedentre")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DATEDENTRE");

                    b.Property<string>("Datedeprise")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DATEDEPRISE");

                    b.Property<string>("Datenaiss")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DATENAISS");

                    b.Property<string>("Dec")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DEC");

                    b.Property<string>("Demav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DEMAV");

                    b.Property<string>("Diplomeac")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DIPLOMEAC");

                    b.Property<string>("Diplomeped")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DIPLOMEPED");

                    b.Property<string>("Dou")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DOU");

                    b.Property<string>("Dxemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("DXEMAV");

                    b.Property<string>("Fonction")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("FONCTION");

                    b.Property<string>("Hemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("HEMAV");

                    b.Property<string>("Lieudenaiss")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("LIEUDENAISS");

                    b.Property<string>("Matiere")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("MATIERE");

                    b.Property<string>("Matricule")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("MATRICULE");

                    b.Property<string>("Nemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("NEMAV");

                    b.Property<string>("NomEtPrenoms")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("NOM_ET_PRENOMS");

                    b.Property<string>("Onemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("ONEMAV");

                    b.Property<string>("Perav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("PERAV");

                    b.Property<string>("Photo")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<string>("Qemav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("QEMAV");

                    b.Property<string>("Quat")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("QUAT");

                    b.Property<string>("Quin")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("QUIN");

                    b.Property<string>("Seiz")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SEIZ");

                    b.Property<string>("Semav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SEMAV");

                    b.Property<string>("Sepmav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SEPMAV");

                    b.Property<string>("Sexe")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("SEXE");

                    b.Property<string>("Statut")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("STATUT");

                    b.Property<string>("Temav")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("TEMAV");

                    b.Property<string>("Trei")
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("TREI");

                    b.HasKey("Num");

                    b.ToTable("BASE", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
